[package]
name = "osc-ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
osc-ir = { path = "../osc-ir", features = ["alloc", "serde", "osc10"] }
osc-codec-msgpack = { path = "../osc-codec-msgpack" }
